desc "Create on Developer portal and App Store Connect"
lane :create_app do
  create_app_online # produce
end

platform :ios do
  before_all do
    Dotenv.load ".env.ios"
  end

  desc "Syns signing"
  lane :signing do
    sync_code_signing # match

    # singleton global access to information after actions run
    mapping = Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]

    # update_code_signing_settings will modify xcode project that is not good
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "Build binary"
  lane :build do
    signing
  end

  desc "Send binary to app store"
  lane :release do
    build
  end
end

platform :mac do
  desc "Syns signing"
  lane :signing do

  end

  desc "Build binary"
  lane :build do

  end

  desc "Send binary to app store"
  lane :release do

  end
end
